list_col = [{'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/', 'name': 'Монте Тиберио',
             'color': ['белый', 'бежевый', 'чёрный'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['60x9.5', '60x60', '60x30', '60x119.5', '49.5x42.3'], 'price': '1767'},
            {'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/', 'name': 'Onyx Smoke',
             'color': ['серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['60x60', '120x60', '120x3', '120x1.5'], 'price': '2390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/atlantic-16647/', 'name': 'Atlantic White',
             'color': ['белый', 'серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['60x60', '120x60', '120x3', '120x1.5'], 'price': '1690'},
            {'link': 'https://www.rusplitka.ru/products/italon/charme-8386/', 'name': 'Charme Floor Project',
             'color': ['белый', 'бежевый', 'коричневый'], 'coutry': 'Россия', 'proiz': 'Italon',
             'size': ['7.2x7.2', '59x59', '15x25'], 'price': '2000'},
            {'link': 'https://www.rusplitka.ru/products/laparet/cassiopea-15639/', 'name': 'Cassiopea',
             'color': ['белый', 'серый'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['60x2.9', '60x1.6', '5x60', '30x60', '30x30'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/polaris-bezhevyy-15675/', 'name': 'Polaris Бежевый',
             'color': ['коричневый', 'бежевый', 'серый', 'белый', 'бордовый', 'чёрный', 'фиолетовый', 'золотой'],
             'coutry': 'Россия', 'proiz': 'Laparet', 'size': ['60x2.9', '60x1.6', '40x40', '38.5x38.5', '30x30'],
             'price': '950'}, {'link': 'https://www.rusplitka.ru/products/laparet/concrete-14028/', 'name': 'Concrete',
                               'color': ['серый', 'бежевый', 'светло-серый', 'золотой'], 'coutry': 'Россия',
                               'proiz': 'Laparet', 'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'],
                               'price': '21'},
            {'link': 'https://www.rusplitka.ru/products/laparet/crystal-14031/', 'name': 'Crystal',
             'color': ['серый', 'бежевый', 'белый', 'чёрный', 'коричневый'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['6x60', '60x2.9', '60x1.6', '40x40', '30x60'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/genesis-14032/', 'name': 'Genesis',
             'color': ['коричневый', 'бежевый', 'белый', 'серый'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['6x60', '60x2.9', '60x1.6', '40x40', '30x60'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/plazma-14033/', 'name': 'Plazma',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/vega-seryy-13314/', 'name': 'Vega серый',
             'color': ['серый', 'светло-серый', 'темно-серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['60x2.9', '60x1.6', '30x30', '20x60', '0.8x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/echo-14029/', 'name': 'Echo',
             'color': ['серый', 'бежевый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/tabu-14030/', 'name': 'Tabu',
             'color': ['белый', 'чёрный', 'серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Laparet',
             'size': ['60x2.9', '60x1.6', '40x40', '30x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/extra-14034/', 'name': 'Extra',
             'color': ['белый', 'серый', 'бежевый', 'коричневый', 'серо-бежевый'], 'coutry': 'Россия',
             'proiz': 'Laparet', 'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/nova-10779/', 'name': 'Nova',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/rainfall-9673/', 'name': 'Rainfall',
             'color': ['яркий', 'голубой', 'белый', 'бирюзовый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x75', '50x3', '50x25', '41x41', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/rejina-10514/', 'name': 'Rejina',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x7.5', '60x3', '60x20', '41x41'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/almaceramica/roxana-14473/', 'name': 'Roxana',
             'color': ['бежевый', 'кремовый'], 'coutry': 'Россия', 'proiz': 'Alma Ceramica',
             'size': ['60x6', '60x20', '41.8x41.8'], 'price': '1290'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/nizida-9497/', 'name': 'Низида',
             'color': ['бежевый', 'коричневый', 'серый', 'светло-серый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['25x8', '25x75'], 'price': '1000'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/vitrage-16799/', 'name': 'Витраж',
             'color': ['золотой', 'белый', 'оранжевый', 'жёлтый', 'голубой', 'синий', 'многоцветный', 'яркий'],
             'coutry': 'Россия', 'proiz': 'Kerama Marazzi', 'size': ['30x30', '20x0.6', '15x2', '15x15', '0.6x20'],
             'price': '1453'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/virdzhiliano-9468/', 'name': 'Вирджилиано',
             'color': ['бежевый', 'серый', 'белый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['60x7.2', '30x7.2', '30x60', '30x30', '30x2.5'], 'price': '1904'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/kapodimonte-9477/', 'name': 'Каподимонте',
             'color': ['голубой', 'бежевый', 'белый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['60x14.5', '33x33', '30x60', '30x5', '30x30'], 'price': '1030'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/mayori-9473/', 'name': 'Майори',
             'color': ['белый', 'чёрный', 'голубой'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['90x90', '89.5x30', '7.2x30'], 'price': '2559'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/dorato-16804/', 'name': 'Дорато',
             'color': ['белый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['8.5x28.5', '2x25', '20x2', '20x0.6'], 'price': '1506'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/carelli-16782/', 'name': 'Карелли',
             'color': ['бежевый', 'белый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['60x60', '60x15.5', '30x60', '30x30', '30x3.4'], 'price': '1587'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/montanelli-16806/', 'name': 'Монтанелли',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi', 'size': ['7.4x15', '1.5x15'],
             'price': '1729'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/navili-16889/', 'name': 'Навильи',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi', 'size': ['15x15', '1.5x15'],
             'price': '1411'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/siyanie-14678/', 'name': 'Сияние',
             'color': ['кремовый', 'голубой', 'бежевый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['40.2x40.2', '25x5.4', '25x40'], 'price': '718'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/floral-14679/', 'name': 'Флораль',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['7.7x7.7', '7.2x40', '40.2x7.7', '40.2x40.2', '3x40'], 'price': '849'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/cuzani-16789/', 'name': 'Кузани',
             'color': ['бежевый', 'серо-бежевый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['50x6.3', '20x6.3', '20x50', '20x5', '20x2'], 'price': '1130'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/gran-pale-12382/', 'name': 'Гран Пале',
             'color': ['серый', 'белый', 'бежевый', 'коричневый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['6x40', '50.2x50.2', '25x5.5', '25x5.4', '25x40'], 'price': '980'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/giardini-16775/', 'name': 'Джардини',
             'color': ['зелёный', 'бежевый', 'серый', 'темно-серый', 'белый'], 'coutry': 'Россия',
             'proiz': 'Kerama Marazzi', 'size': ['60x60', '60x15', '45x37.5', '40x7.3', '40x120'], 'price': '2795'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/castiglioni-16797/', 'name': 'Кастильони',
             'color': ['белый', 'чёрный'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['40x7.2', '40x3.4', '15x40'], 'price': '1175'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/sempione-16779/', 'name': 'Семпионе',
             'color': ['бежевый', 'серый', 'белый', 'коричневый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['30x89.5'], 'price': '2607'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/spiga-16798/', 'name': 'Спига',
             'color': ['бежевый', 'голубой', 'золотой', 'белый', 'чёрный'], 'coutry': 'Россия',
             'proiz': 'Kerama Marazzi', 'size': ['40x7.2', '40x3.4', '15x40'], 'price': '1237'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/stelline-16790/', 'name': 'Стеллине',
             'color': ['бежевый', 'серый', 'кремовый', 'красный'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['50x6.3', '40.2x40.2', '20x6.3', '20x50', '20x5'], 'price': '1260'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/stemma-16796/', 'name': 'Стемма',
             'color': ['коричневый', 'белый', 'серый', 'бежевый', 'болотный', 'серо-бежевый'], 'coutry': 'Россия',
             'proiz': 'Kerama Marazzi', 'size': ['9.9x9.9', '9.8x9.8', '24x24', '20x6.3', '20x3.6'], 'price': '972'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/teatro-16785/', 'name': 'Театро',
             'color': ['бежевый', 'коричневый'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['50.2x50.2', '50.2x16.5', '25x75', '25x5.5', '25x2.5'], 'price': '1904'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/turati-16793/', 'name': 'Турати',
             'color': ['кремовый', 'сиреневый', 'зелёный'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
             'size': ['20x5', '20x30', '20x2', '20x10'], 'price': '880'}]
