coll_data = [{'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/', 'name': 'Монте Тиберио',
              'color': ['белый', 'бежевый', 'чёрный'], 'coutry': 'Россия', 'proiz': 'Kerama Marazzi',
              'size': ['60x9.5', '60x60', '60x30', '60x119.5', '49.5x42.3'], 'price': '1767',
              'xarakt': {'Производитель': 'Kerama Marazzi', 'Страна': 'Россия',
                         'Размер': '60x119.5;60x60;30x119.5;60x9.5;10.7x119.5;238.5x119.5;33x119.5;33x33;60x30;119.5x238.5;2.4x8;2.9x8;39.6x8;49.5x40.2;49.5x42.3',
                         'Цвет': 'белый;бежевый;чёрный',
                         'Помещение': 'для ванной;для кухни;для прихожей;для гостиной;для туалета;для спальни;для общественных помещений;на теплый пол;для фартука',
                         'Назначение': 'напольный;декор;декоративная вставка;плинтус;ступень;подступенник'},
              'image': ['https://www.rusplitka.ru/upload/iblock/72b/m0t1hy9iwgto3bdzkj5zsrs7azz3n09p.jpg',
                        'https://www.rusplitka.ru/upload/iblock/898/53pg5ifhx8i0utr5l9qpmh52ruyhh9qp.jpg',
                        'https://www.rusplitka.ru/upload/iblock/423/7vy84sncwetu2usnwc850cgaz6kfaa56.jpg',
                        'https://www.rusplitka.ru/upload/iblock/245/blhynmrt03dtocdr4osmktvkrif7gmjt.jpg',
                        'https://www.rusplitka.ru/upload/iblock/701/usykyezn07mr8q3t73ek5exh1c811wtx.jpg',
                        'https://www.rusplitka.ru/upload/iblock/1b5/ub20fon8psky593cyfa7ce5bzx3xbzax.jpg',
                        'https://www.rusplitka.ru/upload/iblock/e7a/flo7t3mwqyhnois13wgu9e6te545c7j0.jpg',
                        'https://www.rusplitka.ru/upload/iblock/dc2/fhv1hafkjex2wauz9y370y1e962jmwi1.jpg'],
              'full_name': 'Плитка напольная Kerama Marazzi Монте Тиберио', 'plu_data': [{
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-tiberio-obreznoy-1195x2385-sg590000r-93136/',
                                                                                             'name': 'SG590000R Керамогранит Монте Тиберио Обрезной 119,5x238,5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG590000R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-teberio-monte-tiberio-obreznoy-sg523200r-33601/',
                                                                                             'name': 'SG523200R Керамогранит Монте Тиберио Серый обрезной',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG523200R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-teberio-monte-tiberio-obreznoy-sg507100r-33599/',
                                                                                             'name': 'SG507100R Керамогранит Монте Тиберио Серый обрезной',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507100R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-teberio-monte-tiberio-lappatirovannyy-sg507102r-33600/',
                                                                                             'name': 'SG507102R Керамогранит Монте Тиберио Серый лаппатированный',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507102R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-teberio-monte-tiberio-lappatirovannyy-sg523202r-33602/',
                                                                                             'name': 'SG523202R Керамогранит Монте Тиберио Серый лаппатированный',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG523202R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-turnon-monte-tiberio-lappatirovannyy-60h60-sg622602r-76080/',
                                                                                             'name': 'SG622602R Керамогранит Монте Тиберио Лаппатированный 60х60',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622602R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-tiberio-lappatirovannyy-1195h2385-sg590002r-93137/',
                                                                                             'name': 'SG590002R Керамогранит Монте Тиберио Лаппатированный 119,5х238,5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG590002R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-tiberio-bezh-lappatirovannyy-sg592002r-93140/',
                                                                                             'name': 'SG592002R Керамогранит Монте Тиберио Беж лаппатированный',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG592002R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-tiberio-bezh-lappatirovannyy-60-sg651502r-132255/',
                                                                                             'name': 'SG651502R Керамогранит Монте Тиберио Беж лаппатированный 60',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG651502R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-monte-tiberio-bezh-lappatirovannyy-60x1195-sg564502r-93135/',
                                                                                             'name': 'SG564502R Керамогранит Монте Тиберио Беж лаппатированный 60x119,5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG564502R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/keramogranit-ginardo-monte-tiberio-obreznoy-naturalnyy-sg622600r-93783/',
                                                                                             'name': 'SG622600R Керамогранит Монте Тиберио обрезной натуральный',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622600R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/naturalnyy_obreznoy_9mm-198397/',
                                                                                             'name': 'SG507120R Керамогранит Монте Тиберио Натуральный обрезной 9мм 60x119.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507120R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannyy_obreznoy_9mm-198398/',
                                                                                             'name': 'SG507122R Керамогранит Монте Тиберио Лаппатированный обрезной 9мм 60x119.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507122R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/bezhevyy_lappatirovannyy_obreznoy_9mm-198399/',
                                                                                             'name': 'SG564522R Керамогранит Монте Тиберио Бежевый лаппатированный обрезной 9мм 60x119.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG564522R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/obreznoy_60x60_9mm-198400/',
                                                                                             'name': 'SG622620R Керамогранит Монте Тиберио Обрезной 60x60 9мм',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622620R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/bezhevyy_lappatirovannyy_obreznoy_60x60_9mm-198402/',
                                                                                             'name': 'SG651522R Керамогранит Монте Тиберио Бежевый лаппатированный обрезной 60x60 9мм',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG651522R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannyy_obreznoy_60x60_9mm-198401/',
                                                                                             'name': 'SG622622R Керамогранит Монте Тиберио Лаппатированный обрезной 60x60 9мм',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622622R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/stupen-monte-tiberio-lappatirovannyy-uglovaya-universalnaya-kleenaya-33h33-sg507102rgca-85562/',
                                                                                             'name': 'SG507102R/GCA Ступень Монте Тиберио Лаппатированный угловая универсальная клееная 33х33',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507102R/GCA',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/stupen-prado-kleenaya-monte-tiberio-lappatirovannaya-33h1195-sg507102rgcf-93014/',
                                                                                             'name': 'SG507102R/GCF Ступень Монте Тиберио Клееная лаппатированная 33х119,5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507102R/GCF',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannaya_119_5x30-183210/',
                                                                                             'name': 'Ступень Монте Тиберио Лаппатированная 119.5x30',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'no_art_15714',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/dekor-keramogranit-monte-tiberio-nabornyy-d95x402-id75-93141/',
                                                                                             'name': 'ID75 Декор Монте Тиберио Наборный Д49.5x40',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'ID75',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/obreznaya_60x30-183216/',
                                                                                             'name': 'SG622600R/GR Ступень Монте Тиберио Обрезная 60x30',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622600R/GR',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/belyy_119_5_238_5-192743/',
                                                                                             'name': 'SG591702R Декор Монте Тиберио Белый 119.5*238.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG591702R',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/nabornyy_9mm-198403/',
                                                                                             'name': 'ID75T Декор Монте Тиберио Наборный 9мм 49.5x40.2',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'ID75T',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/obreznoy_nasechki_9mm-198404/',
                                                                                             'name': 'SG507120R/GR Ступень Монте Тиберио Обрезной насечки 9мм 30x119.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507120R/GR',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/uglovaya_kleenaya_lappatirovannyy_9mm-198406/',
                                                                                             'name': 'SG507122R/GCA Ступень Монте Тиберио Угловая клееная лаппатированный 9мм 33x33',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507122R/GCA',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/kleenaya_9mm-198407/',
                                                                                             'name': 'SG507122R/GCF Ступень Монте Тиберио Клееная 9мм 33x119.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507122R/GCF',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/obreznoy_30x60_9mm-198409/',
                                                                                             'name': 'SG622620R/GR Ступень Монте Тиберио Обрезной 30x60 9мм',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622620R/GR',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/podstupenok-prado-monte-tiberio-1195h107-sg507102r1-93013/',
                                                                                             'name': 'SG507102R/1 Подступенник Монте Тиберио 119.5х10.7',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507102R/1',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/obreznoy_60x9_5-183215/',
                                                                                             'name': 'SG622600R/6BT Плинтус Монте Тиберио Обрезной 60x9.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622600R/6BT',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannyy_60x9_5-183217/',
                                                                                             'name': 'SG622602R/6BT Плинтус Монте Тиберио Лаппатированный 60x9.5',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622602R/6BT',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/ugol_vnutrenniy-183213/',
                                                                                             'name': 'SG6226/AGI Декоративная вставка Монте Тиберио Угол внутренний',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG6226/AGI',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/ugol_vneshniy-183212/',
                                                                                             'name': 'SG6226/AGE Декоративная вставка Монте Тиберио Угол внешний',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG6226/AGE',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannyy_39_6x8-183214/',
                                                                                             'name': 'SG6226/BTL Плинтус Монте Тиберио Лаппатированный 39.6x8',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG6226/BTL',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannyy_119_5x10_7-183211/',
                                                                                             'name': 'SG507102R/5 Подступенник Монте Тиберио Лаппатированный 119.5x10.7',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507102R/5',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannyy_119_5x10_7_9mm-198405/',
                                                                                             'name': 'SG507122R/5 Подступенник Монте Тиберио Лаппатированный 119.5x10.7 9мм',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG507122R/5',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/obreznoy_60x9_5_9mm-198408/',
                                                                                             'name': 'SG622620R/6BT Плинтус Монте Тиберио Обрезной 60x9.5 9мм',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622620R/6BT',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'},
                                                                                         {
                                                                                             'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/lappatirovannyy_60x9_5_9mm-198410/',
                                                                                             'name': 'SG622622R/6BT Плинтус Монте Тиберио Лаппатированный 60x9.5 9мм',
                                                                                             'coutry': 'Россия',
                                                                                             'artikl': 'SG622622R/6BT',
                                                                                             'proiz': 'Kerama Marazzi',
                                                                                             'collection': 'Монте Тиберио'}]},
             {'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/', 'name': 'Onyx Smoke',
              'color': ['серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'Laparet',
              'size': ['60x60', '120x60', '120x3', '120x1.5'], 'price': '2390',
              'xarakt': {'Производитель': 'Laparet', 'Страна': 'Россия', 'Размер': '120x1.5;120x3;120x60;60x60',
                         'Цвет': 'серый;золотой', 'Помещение': 'для ванной;для туалета;на теплый пол',
                         'Назначение': 'напольный;бордюр'},
              'image': ['https://www.rusplitka.ru/upload/iblock/2e1/f9ujhmsglgt6ibywgvcfwip10plb07ud.jpg'],
              'full_name': 'Керамогранит Laparet Onyx Smoke', 'plu_data': [{
                                                                               'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/keramogranit-onyx-onyx-smoke-60x60-polirovannyy-114635/',
                                                                               'name': 'Керамогранит Onyx Smoke 60x60 полированный',
                                                                               'coutry': 'Индия',
                                                                               'artikl': 'no_art_60526',
                                                                               'proiz': 'Laparet',
                                                                               'collection': 'Onyx Smoke'}, {
                                                                               'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/keramogranit-onyx-onyx-smoke-60x120-polirovannyy-114634/',
                                                                               'name': 'Керамогранит Onyx Smoke 120x60 полированный',
                                                                               'coutry': 'Индия',
                                                                               'artikl': 'no_art_29825',
                                                                               'proiz': 'Laparet',
                                                                               'collection': 'Onyx Smoke'}, {
                                                                               'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/bordyur-nastennyy-infinito-metal-zoloto-glyancevoe-120x15-144496/',
                                                                               'name': 'Бордюр Onyx Smoke Метал. Золото Глянцевое 120x1.5',
                                                                               'coutry': 'Россия',
                                                                               'artikl': 'no_art_53061',
                                                                               'proiz': 'Laparet',
                                                                               'collection': 'Onyx Smoke'}, {
                                                                               'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/bordyur-nastennyy-antalya-bianco-metal-zoloto-glyancevoe-120x3-144488/',
                                                                               'name': 'Бордюр Onyx Smoke Метал. Золото Глянцевое 120x3',
                                                                               'coutry': 'Россия',
                                                                               'artikl': 'no_art_76447',
                                                                               'proiz': 'Laparet',
                                                                               'collection': 'Onyx Smoke'}, {
                                                                               'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/bordyur-nastennyy-antalya-bianco-metal-serebro-glyancevoe-120x15-144489/',
                                                                               'name': 'Бордюр Onyx Smoke Метал. Серебро Глянцевое 120x1.5',
                                                                               'coutry': 'Россия',
                                                                               'artikl': 'no_art_99026',
                                                                               'proiz': 'Laparet',
                                                                               'collection': 'Onyx Smoke'}, {
                                                                               'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/bordyur-nastennyy-antalya-bianco-metal-serebro-glyancevoe-120x3-144490/',
                                                                               'name': 'Бордюр Onyx Smoke Метал. Серебро Глянцевое 120x3',
                                                                               'coutry': 'Россия',
                                                                               'artikl': 'no_art_72658',
                                                                               'proiz': 'Laparet',
                                                                               'collection': 'Onyx Smoke'}]}]
