list_col = [{'link': 'https://www.rusplitka.ru/products/alta-cera/rainfall-9673/', 'name': 'Rainfall',
             'color': ['яркий', 'голубой', 'белый', 'бирюзовый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x75', '50x3', '50x25', '41x41', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/rejina-10514/', 'name': 'Rejina',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x7.5', '60x3', '60x20', '41x41'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/wood-white-9676/', 'name': 'Wood White',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['24.9x50'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/nova-10779/', 'name': 'Nova',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/sonata-9629/', 'name': 'Sonata',
             'color': ['серый', 'светло-серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x6.7', '50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/blik-azul-8853/', 'name': 'Blik Azul',
             'color': ['голубой', 'белый', 'фиолетовый', 'бордовый', 'розовый', 'сиреневый'], 'coutry': 'Россия',
             'proiz': 'AltaCera', 'size': ['50x5', '50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/deco-13363/', 'name': 'Deco',
             'color': ['белый', 'серый', 'бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/fluence-9653/', 'name': 'Fluence',
             'color': ['голубой', 'белый', 'яркий', 'бирюзовый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x6.7', '50x25', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/imprint-11645/', 'name': 'Imprint',
             'color': ['бежевый', 'кремовый', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x20', '60x1.3', '41x41', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/oliver-14074/', 'name': 'Oliver',
             'color': ['белый', 'голубой', 'бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/pion-crema-8855/', 'name': 'Pion Crema',
             'color': ['голубой', 'бежевый', 'кремовый', 'белый', 'бордовый', 'фиолетовый', 'сиреневый'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x5', '50x24.9', '49.8x50', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/vesta-11647/', 'name': 'Vesta',
             'color': ['белый', 'серый', 'чёрный'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x20', '60x1.3', '41x41', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/dolce-16022/', 'name': 'Dolce',
             'color': ['белый', 'чёрный', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x1.3', '41x41', '20x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/formwork-16142/', 'name': 'Formwork',
             'color': ['белый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3', '41x41', '20x60'],
             'price': '1390'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/sanders-16023/', 'name': 'Sanders',
                                'color': ['белый', 'бежевый', 'голубой', 'зелёный', 'золотой'], 'coutry': 'Россия',
                                'proiz': 'AltaCera', 'size': ['60x1.3', '41x41', '20x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/vertus-16624/', 'name': 'Vertus',
             'color': ['белый', 'бежевый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/briole-17778/', 'name': 'Briole',
             'color': ['бежевый', 'белый', 'голубой', 'серый', 'светло-серый', 'яркий', 'золотой'], 'coutry': 'Россия',
             'proiz': 'AltaCera', 'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/eleganza-17673/', 'name': 'Eleganza',
             'color': ['белый', 'бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x4', '50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/artdeco-19230/', 'name': 'Artdeco',
             'color': ['бежевый', 'белый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/avenue-19232/', 'name': 'Avenue',
             'color': ['белый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x1.3', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/bayron-19251/', 'name': 'Bayron',
             'color': ['белый', 'серый', 'бежевый', 'светло-серый', 'яркий', 'золотой'], 'coutry': 'Россия',
             'proiz': 'AltaCera', 'size': ['50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/sens-19271/', 'name': 'Sens',
             'color': ['серый', 'светло-серый', 'золотой', 'белый', 'яркий'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/paradise-19273/', 'name': 'Paradise',
             'color': ['белый', 'бежевый', 'яркий', 'зелёный', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['75x50', '50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/esprit-19253/', 'name': 'Esprit',
             'color': ['коричневый', 'белый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/flow-19254/', 'name': 'Flow',
             'color': ['белый', 'голубой', 'серый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/interni-gold-19262/', 'name': 'Interni Gold',
             'color': ['бежевый', 'кремовый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x50', '50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/village-19284/', 'name': 'Village',
             'color': ['кремовый', 'бежевый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/portland-19280/', 'name': 'Portland',
             'color': ['бежевый', 'многоцветный', 'яркий', 'белый', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/enigma-19275/', 'name': 'Enigma',
             'color': ['кремовый', 'бирюзовый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/resort-19281/', 'name': 'Resort',
             'color': ['коричневый', 'белый', 'золотой', 'яркий'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/veronica-19283/', 'name': 'Veronica',
             'color': ['бежевый', 'золотой', 'кремовый', 'яркий'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x49.8', '50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/triangle-19282/', 'name': 'Triangle',
             'color': ['бежевый', 'белый', 'кремовый', 'серый', 'яркий', 'золотой'], 'coutry': 'Россия',
             'proiz': 'AltaCera', 'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/antique-19274/', 'name': 'Antique',
             'color': ['белый', 'бежевый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/modern-19279/', 'name': 'Modern',
             'color': ['белый', 'серый', 'золотой', 'яркий'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/petra-14335/', 'name': 'Petra',
             'color': ['песочный', 'коричневый', 'бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x4', '50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/megapolis-16582/', 'name': 'Megapolis',
             'color': ['серый', 'бежевый', 'чёрный'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x49.8', '50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/palm-12555/', 'name': 'Palm', 'color': ['золотой'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/shape-13367/', 'name': 'Shape',
             'color': ['белый', 'серый', 'светло-серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/bloom-17595/', 'name': 'Bloom', 'color': ['золотой'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/julia-19277/', 'name': 'Julia',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/atlantic-19231/', 'name': 'Atlantic',
             'color': ['белый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x1.3', '41x41', '25x50'],
             'price': '1350'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/interni-19261/', 'name': 'Interni',
                                'color': ['серый', 'бежевый', 'светло-серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                                'size': ['50x50', '50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/miracle-19278/', 'name': 'Miracle',
             'color': ['белый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/eterna-19276/', 'name': 'Eterna',
             'color': ['белый', 'сиреневый', 'серо-бежевый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/fern-14339/', 'name': 'Fern',
             'color': ['серый', 'белый', 'фиолетовый', 'сиреневый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x49.8', '50x24.9', '50x1.3', '41x41', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/elite-10511/', 'name': 'Elite', 'color': ['бежевый'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x7.5', '60x3'], 'price': '839'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/felicity-groundy--9764/', 'name': 'Felicity Groundy',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x20', '41x41'],
             'price': '1390'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/smalta-16623/', 'name': 'Smalta',
                                'color': ['серый', 'белый', 'коричневый', 'светло-серый'], 'coutry': 'Россия',
                                'proiz': 'AltaCera', 'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/wood-beige-9677/', 'name': 'Wood Beige',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['24.9x50'], 'price': '750'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/antares-9445/', 'name': 'Antares',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['41x41'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/algorithm-12554/', 'name': 'Algorithm',
             'color': ['белый', 'чёрный', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/bella-11644/', 'name': 'Bella',
             'color': ['белый', 'серый', 'чёрный'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x20', '60x1.3', '41x41', '30x30', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/orion-9632/', 'name': 'Orion',
             'color': ['серый', 'светло-серый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x24.9', '41x41'],
             'price': '1350'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/flexion-9654/', 'name': 'Flexion',
                                'color': ['яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                                'size': ['50x1.3'], 'price': '295'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/fresco-10512/', 'name': 'Fresco',
             'color': ['бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x20', '41x41'],
             'price': '1390'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/glent-11881/', 'name': 'Glent',
                                'color': ['белый', 'чёрный', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                                'size': ['50x24.9', '50x1.3', '41x41', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/honey-13366/', 'name': 'Honey',
             'color': ['белый', 'бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x24.9', '41x41'],
             'price': '1350'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/lotus-8868/', 'name': 'Lotus',
                                'color': ['белый', 'фиолетовый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                                'size': ['50x25', '41x41'], 'price': '950'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/luxury-9665/', 'name': 'Luxury',
             'color': ['белый', 'яркий', 'голубой', 'бирюзовый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x6.7', '50x25', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/space-11646/', 'name': 'Space', 'color': ['серый'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/stingray-brown-13368/', 'name': 'Stingray Brown',
             'color': ['серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'],
             'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/story-11880/', 'name': 'Story', 'color': ['серый'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/fantasy-16065/', 'name': 'Fantasy',
             'color': ['белый', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3', '41x41'],
             'price': '1390'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/diamond-17596/', 'name': 'Diamond',
                                'color': ['белый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                                'size': ['60x20', '60x1.3', '41x41'], 'price': '1320'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/moon-17592/', 'name': 'Moon',
             'color': ['серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3', '41x41'],
             'price': '1390'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/oxford-16622/', 'name': 'Oxford',
                                'color': ['серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                                'size': ['60x1.3', '41x41'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/albero-17382/', 'name': 'Albero',
             'color': ['бежевый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x1.3', '3x50'], 'price': '295'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/elemento-19252/', 'name': 'Elemento',
             'color': ['белый', 'бежевый', 'серый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x1.3', '41x41', '25x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/magic-8867/', 'name': 'Magic', 'color': ['розовый'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x5', '24.9x50'], 'price': '45'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/detroit-21754/', 'name': 'Detroit',
             'color': ['белый', 'бежевый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x60', '50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/islandia-21755/', 'name': 'Islandia',
             'color': ['бежевый', 'белый', 'серый', 'яркий', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/blik-beige-8851/', 'name': 'Blik Crema',
             'color': ['бежевый', 'кремовый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x5', '50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/deco-sky-13364/', 'name': 'Deco Sky',
             'color': ['белый', 'серый', 'голубой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/rhombus-blue-14336/', 'name': 'Rhombus',
             'color': ['коричневый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x1.3'],
             'price': '324'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/urban-14338/', 'name': 'Urban',
                               'color': ['серый', 'белый', 'сиреневый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                               'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/portofino-16555/', 'name': 'Portofino',
             'color': ['бежевый', 'коричневый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x1.3', '41x41'],
             'price': '1390'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/liberto-21756/', 'name': 'Liberto',
                                'color': ['серый', 'светлый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                                'size': ['60x60', '50x1.3', '24.9x50'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/arrow-12602/', 'name': 'Arrow', 'color': ['золотой'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/glory-10606/', 'name': 'Glory', 'color': ['бежевый'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x7.5', '60x3'], 'price': '839'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/lantana-12094/', 'name': 'Lantana',
             'color': ['золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/orleans-11879/', 'name': 'Orleans',
             'color': ['золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/funny-16229/', 'name': 'Fanny', 'color': ['золотой'],
             'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/lima-21453/', 'name': 'Lima',
             'color': ['белый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x60', '50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/albion-21753/', 'name': 'Albion',
             'color': ['белый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x60', '50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/santos-21759/', 'name': 'Santos',
             'color': ['серый', 'белый', 'бежевый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/palmira-21758/', 'name': 'Palmira',
             'color': ['серо-бежевый', 'белый', 'серый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/napoli-21757/', 'name': 'Napoli',
             'color': ['серый', 'белый', 'синий', 'жёлтый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x60', '50x24.9', '50x1.3'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/stingray-graphite-13369/',
             'name': 'Stingray Graphite', 'color': ['серый', 'золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera',
             'size': ['60x1.3'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/geometrica-9657/', 'name': 'Geometrica',
             'color': ['белый', 'фиолетовый'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['50x25', '41x41'],
             'price': '950'}, {'link': 'https://www.rusplitka.ru/products/alta-cera/mix-9672/', 'name': 'Mix',
                               'color': ['белый', 'фиолетовый'], 'coutry': 'Россия', 'proiz': 'AltaCera',
                               'size': ['50x25', '41x41'], 'price': '950'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/morocco-12603/', 'name': 'Morocco',
             'color': ['золотой'], 'coutry': 'Россия', 'proiz': 'AltaCera', 'size': ['60x1.3'], 'price': '390'}]

