list_col = [{'link': 'https://www.rusplitka.ru/products/kerama-marazzi/monte-teberio-9483/', 'name': 'Монте Тиберио',
             'color': ['белый', 'бежевый', 'чёрный'], 'coutry': 'Россия',
             'size': ['60x9.5', '60x60', '60x30', '60x119.5', '49.5x42.3'], 'price': '1767'},
            {'link': 'https://www.rusplitka.ru/products/laparet/onyx-smoke--16658/', 'name': 'Onyx Smoke',
             'color': ['серый', 'золотой'], 'coutry': 'Россия', 'size': ['60x60', '120x60', '120x3', '120x1.5'],
             'price': '2390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/atlantic-16647/', 'name': 'Atlantic White',
             'color': ['белый', 'серый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x60', '120x60', '120x3', '120x1.5'], 'price': '1690'},
            {'link': 'https://www.rusplitka.ru/products/italon/charme-8386/', 'name': 'Charme Floor Project',
             'color': ['белый', 'бежевый', 'коричневый'], 'coutry': 'Россия', 'size': ['7.2x7.2', '59x59', '15x25'],
             'price': '2000'},
            {'link': 'https://www.rusplitka.ru/products/laparet/cassiopea-15639/', 'name': 'Cassiopea',
             'color': ['белый', 'серый'], 'coutry': 'Россия', 'size': ['60x2.9', '60x1.6', '5x60', '30x60', '30x30'],
             'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/polaris-bezhevyy-15675/', 'name': 'Polaris Бежевый',
             'color': ['коричневый', 'бежевый', 'серый', 'белый', 'бордовый', 'чёрный', 'фиолетовый', 'золотой'],
             'coutry': 'Россия', 'size': ['60x2.9', '60x1.6', '40x40', '38.5x38.5', '30x30'], 'price': '950'},
            {'link': 'https://www.rusplitka.ru/products/laparet/concrete-14028/', 'name': 'Concrete',
             'color': ['серый', 'бежевый', 'светло-серый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'], 'price': '21'},
            {'link': 'https://www.rusplitka.ru/products/laparet/crystal-14031/', 'name': 'Crystal',
             'color': ['серый', 'бежевый', 'белый', 'чёрный', 'коричневый'], 'coutry': 'Россия',
             'size': ['6x60', '60x2.9', '60x1.6', '40x40', '30x60'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/genesis-14032/', 'name': 'Genesis',
             'color': ['коричневый', 'бежевый', 'белый', 'серый'], 'coutry': 'Россия',
             'size': ['6x60', '60x2.9', '60x1.6', '40x40', '30x60'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/plazma-14033/', 'name': 'Plazma',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'],
             'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/vega-seryy-13314/', 'name': 'Vega серый',
             'color': ['серый', 'светло-серый', 'темно-серый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '30x30', '20x60', '0.8x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/echo-14029/', 'name': 'Echo',
             'color': ['серый', 'бежевый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/tabu-14030/', 'name': 'Tabu',
             'color': ['белый', 'чёрный', 'серый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '40x40', '30x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/extra-14034/', 'name': 'Extra',
             'color': ['белый', 'серый', 'бежевый', 'коричневый', 'серо-бежевый'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '40x40', '30x60', '30x30'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/nova-10779/', 'name': 'Nova',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'size': ['50x24.9', '50x1.3', '41x41'], 'price': '1350'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/rainfall-9673/', 'name': 'Rainfall',
             'color': ['яркий', 'голубой', 'белый', 'бирюзовый', 'серый'], 'coutry': 'Россия',
             'size': ['50x75', '50x3', '50x25', '41x41', '30.5x30.5'], 'price': '1174'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/rejina-10514/', 'name': 'Rejina',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['60x7.5', '60x3', '60x20', '41x41'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/almaceramica/roxana-14473/', 'name': 'Roxana',
             'color': ['бежевый', 'кремовый'], 'coutry': 'Россия', 'size': ['60x6', '60x20', '41.8x41.8'],
             'price': '1290'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/nizida-9497/', 'name': 'Низида',
             'color': ['бежевый', 'коричневый', 'серый', 'светло-серый'], 'coutry': 'Россия', 'size': ['25x8', '25x75'],
             'price': '1000'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/vitrage-16799/', 'name': 'Витраж',
             'color': ['золотой', 'белый', 'оранжевый', 'жёлтый', 'голубой', 'синий', 'многоцветный', 'яркий'],
             'coutry': 'Россия', 'size': ['30x30', '20x0.6', '15x2', '15x15', '0.6x20'], 'price': '1453'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/virdzhiliano-9468/', 'name': 'Вирджилиано',
             'color': ['бежевый', 'серый', 'белый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x7.2', '30x7.2', '30x60', '30x30', '30x2.5'], 'price': '1904'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/kapodimonte-9477/', 'name': 'Каподимонте',
             'color': ['голубой', 'бежевый', 'белый'], 'coutry': 'Россия',
             'size': ['60x14.5', '33x33', '30x60', '30x5', '30x30'], 'price': '1030'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/mayori-9473/', 'name': 'Майори',
             'color': ['белый', 'чёрный', 'голубой'], 'coutry': 'Россия', 'size': ['90x90', '89.5x30', '7.2x30'],
             'price': '2559'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/dorato-16804/', 'name': 'Дорато',
             'color': ['белый', 'золотой'], 'coutry': 'Россия', 'size': ['8.5x28.5', '2x25', '20x2', '20x0.6'],
             'price': '1506'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/carelli-16782/', 'name': 'Карелли',
             'color': ['бежевый', 'белый'], 'coutry': 'Россия',
             'size': ['60x60', '60x15.5', '30x60', '30x30', '30x3.4'], 'price': '1587'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/montanelli-16806/', 'name': 'Монтанелли',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['7.4x15', '1.5x15'], 'price': '1729'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/navili-16889/', 'name': 'Навильи',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['15x15', '1.5x15'], 'price': '1411'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/siyanie-14678/', 'name': 'Сияние',
             'color': ['кремовый', 'голубой', 'бежевый'], 'coutry': 'Россия', 'size': ['40.2x40.2', '25x5.4', '25x40'],
             'price': '718'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/floral-14679/', 'name': 'Флораль',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['7.7x7.7', '7.2x40', '40.2x7.7', '40.2x40.2', '3x40'],
             'price': '849'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/cuzani-16789/', 'name': 'Кузани',
             'color': ['бежевый', 'серо-бежевый'], 'coutry': 'Россия',
             'size': ['50x6.3', '20x6.3', '20x50', '20x5', '20x2'], 'price': '1130'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/gran-pale-12382/', 'name': 'Гран Пале',
             'color': ['серый', 'белый', 'бежевый', 'коричневый'], 'coutry': 'Россия',
             'size': ['6x40', '50.2x50.2', '25x5.5', '25x5.4', '25x40'], 'price': '980'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/giardini-16775/', 'name': 'Джардини',
             'color': ['зелёный', 'бежевый', 'серый', 'темно-серый', 'белый'], 'coutry': 'Россия',
             'size': ['60x60', '60x15', '45x37.5', '40x7.3', '40x120'], 'price': '2795'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/castiglioni-16797/', 'name': 'Кастильони',
             'color': ['белый', 'чёрный'], 'coutry': 'Россия', 'size': ['40x7.2', '40x3.4', '15x40'], 'price': '1175'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/sempione-16779/', 'name': 'Семпионе',
             'color': ['бежевый', 'серый', 'белый', 'коричневый'], 'coutry': 'Россия', 'size': ['30x89.5'],
             'price': '2607'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/spiga-16798/', 'name': 'Спига',
             'color': ['бежевый', 'голубой', 'золотой', 'белый', 'чёрный'], 'coutry': 'Россия',
             'size': ['40x7.2', '40x3.4', '15x40'], 'price': '1237'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/stelline-16790/', 'name': 'Стеллине',
             'color': ['бежевый', 'серый', 'кремовый', 'красный'], 'coutry': 'Россия',
             'size': ['50x6.3', '40.2x40.2', '20x6.3', '20x50', '20x5'], 'price': '1260'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/stemma-16796/', 'name': 'Стемма',
             'color': ['коричневый', 'белый', 'серый', 'бежевый', 'болотный', 'серо-бежевый'], 'coutry': 'Россия',
             'size': ['9.9x9.9', '9.8x9.8', '24x24', '20x6.3', '20x3.6'], 'price': '972'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/teatro-16785/', 'name': 'Театро',
             'color': ['бежевый', 'коричневый'], 'coutry': 'Россия',
             'size': ['50.2x50.2', '50.2x16.5', '25x75', '25x5.5', '25x2.5'], 'price': '1904'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/turati-16793/', 'name': 'Турати',
             'color': ['кремовый', 'сиреневый', 'зелёный'], 'coutry': 'Россия',
             'size': ['20x5', '20x30', '20x2', '20x10'], 'price': '880'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/mattone-10810/', 'name': 'Маттоне',
             'color': ['бежевый', 'коричневый', 'серый', 'светло-серый'], 'coutry': 'Россия', 'size': ['28.5x8.5'],
             'price': '1310'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/atele-12380/', 'name': 'Ателье',
             'color': ['многоцветный', 'яркий', 'серый', 'чёрный', 'черно-белый', 'белый', 'темно-серый'],
             'coutry': 'Россия', 'size': ['20x20'], 'price': '894'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/lombardia-16787/', 'name': 'Ломбардиа',
             'color': ['бежевый', 'белый', 'розовый', 'серый', 'чёрный', 'темно-серый'], 'coutry': 'Россия',
             'size': ['50x40', '40x6', '25x5.4', '25x40', '20x1.4'], 'price': '873'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/ponti-16795/', 'name': 'Понти',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'size': ['20x20', '20x0.6'], 'price': '937'},
            {'link': 'https://www.rusplitka.ru/products/alta-cera/wood-white-9676/', 'name': 'Wood White',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['24.9x50'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/mramornyy-dvorets-10727/',
             'name': 'Мраморный дворец', 'color': ['бежевый', 'коричневый'], 'coutry': 'Россия',
             'size': ['7.2x7.2', '40.2x7.2', '40.2x40.2', '119.5x238.5'], 'price': '2094'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/danieli-10813/', 'name': 'Даниэли',
             'color': ['яркий', 'золотой', 'бежевый', 'чёрный', 'красный', 'белый'], 'coutry': 'Россия',
             'size': ['30x60', '30x3.4', '30x15', '30x14.5', '30x12'], 'price': '1928'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/astoriya-10740/', 'name': 'Астория',
             'color': ['белый', 'бежевый', 'чёрный'], 'coutry': 'Россия',
             'size': ['50.2x50.2', '25x8', '25x75', '25x5.5'], 'price': '2152'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/borsari-10742/', 'name': 'Борсари',
             'color': ['белый', 'серый', 'коричневый'], 'coutry': 'Россия',
             'size': ['75x50', '75x25', '50.2x8.1', '50.2x50.2', '2x25'], 'price': '1572'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/foskari-11924/', 'name': 'Фоскари',
             'color': ['бирюзовый', 'розовый', 'бежевый'], 'coutry': 'Россия',
             'size': ['5.4x25', '40x25', '30x30', '2x25'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/grenel-12665/', 'name': 'Гренель',
             'color': ['серый', 'светло-серый', 'темно-серый'], 'coutry': 'Россия',
             'size': ['89.5x30', '60x60', '46.8x9.8', '46.8x9', '30x7.2'], 'price': '1761'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/aulenti-16788/', 'name': 'Ауленти',
             'color': ['белый', 'бежевый'], 'coutry': 'Россия', 'size': ['20x50'], 'price': '1064'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/bamboo-16780/', 'name': 'Бамбу',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['60x7.2', '30x7.2', '30x60'], 'price': '1980'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/besana-16783/', 'name': 'Безана',
             'color': ['бежевый', 'серый', 'светло-серый'], 'coutry': 'Россия',
             'size': ['50.2x50.2', '25x75', '25x5.5', '25x25', '25x2'], 'price': '1503'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/borromeo-16786/', 'name': 'Борромео',
             'color': ['голубой', 'бежевый', 'белый', 'золотой'], 'coutry': 'Россия',
             'size': ['25x7.7', '25x40', '25x4', '25x15'], 'price': '970'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/buonarroti-16778/', 'name': 'Буонарроти',
             'color': ['белый', 'темно-серый', 'серый', 'черно-белый'], 'coutry': 'Россия',
             'size': ['60x60', '39x35', '30x89.5', '30x7.2', '30x32'], 'price': '1896'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/velasca-16781/', 'name': 'Веласка',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['60x60', '60x120', '30x7.2', '30x60', '30x5'],
             'price': '1587'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/graffiti-16800/', 'name': 'Граффити',
             'color': ['чёрный', 'серый', 'белый', 'светло-серый', 'темно-серый', 'розовый', 'фиолетовый', 'коричневый',
                       'синий', 'жёлтый'], 'coutry': 'Россия',
             'size': ['89.1x20', '39.6x20', '20x9.9', '20x2', '20x1.4'], 'price': '1212'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/greppi-16776/', 'name': 'Греппи',
             'color': ['чёрный', 'белый', 'коричневый'], 'coutry': 'Россия',
             'size': ['60x60', '60x15.5', '45x37.5', '40x7.3', '40x20'], 'price': '2488'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/darsena-16803/', 'name': 'Дарсена',
             'color': ['золотой', 'голубой', 'синий', 'бирюзовый'], 'coutry': 'Россия',
             'size': ['8.5x28.5', '20x2', '20x0.6', '1.4x20', '0.6x20'], 'price': '1621'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/duomo-16801/', 'name': 'Дуомо',
             'color': ['бежевый'], 'coutry': 'Россия', 'size': ['50.2x50.2', '20x9.9', '20.1x50.2'], 'price': '1142'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/lambro-16777/', 'name': 'Ламбро',
             'color': ['бежевый', 'коричневый', 'светло-серый'], 'coutry': 'Россия', 'size': ['40x120', '20x120'],
             'price': '2231'},
            {'link': 'https://www.rusplitka.ru/products/kerama-marazzi/morando-16784/', 'name': 'Морандо',
             'color': ['белый', 'темно-серый'], 'coutry': 'Россия', 'size': ['25x75'], 'price': '1745'},
            {'link': 'https://www.rusplitka.ru/products/delacora/royal-14746/', 'name': 'Royal',
             'color': ['серый', 'белый', 'голубой', 'светло-серый'], 'coutry': 'Россия',
             'size': ['75x25.3', '74x24.6', '6x25', '6x24.6', '41x41'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/cersanit/sonata-10947/', 'name': 'Sonata',
             'color': ['серый', 'светло-серый'], 'coutry': 'Россия', 'size': ['60x8', '60x20', '42x42'],
             'price': '1210'}, {'link': 'https://www.rusplitka.ru/products/cersanit/navi-10939/', 'name': 'Navi',
                                'color': ['серый', 'розовый', 'светло-серый'], 'coutry': 'Россия',
                                'size': ['44x5', '44x40', '44x20', '42x42'], 'price': '770'},
            {'link': 'https://www.rusplitka.ru/products/cersanit/manhattan-10946/', 'name': 'Manhattan',
             'color': ['белый', 'серый', 'красный'], 'coutry': 'Россия', 'size': ['60x20', '60x2', '42x42'],
             'price': '1210'}, {'link': 'https://www.rusplitka.ru/products/cersanit/alrami-10933/', 'name': 'Alrami',
                                'color': ['серый', 'коричневый', 'светло-серый'], 'coutry': 'Россия',
                                'size': ['44x5', '44x20', '42x42'], 'price': '770'},
            {'link': 'https://www.rusplitka.ru/products/cersanit/atria-10934/', 'name': 'Atria',
             'color': ['бежевый', 'белый'], 'coutry': 'Россия', 'size': ['44x5', '44x20', '42x42'], 'price': '770'},
            {'link': 'https://www.rusplitka.ru/products/cersanit/royal-garden-10969/', 'name': 'Royal Garden',
             'color': ['бежевый', 'коричневый', 'песочный'], 'coutry': 'Россия',
             'size': ['60x4.5', '59.8x29.8', '42x42', '29.7x60'], 'price': '1100'},
            {'link': 'https://www.rusplitka.ru/products/cersanit/illusion-5682/', 'name': 'Illusion',
             'color': ['бежевый', 'серый', 'венге', 'оливковый', 'зелёный'], 'coutry': 'Россия',
             'size': ['5x44', '44x5', '42x42', '30x30', '20x44'], 'price': '860'},
            {'link': 'https://www.rusplitka.ru/products/cersanit/miracle-6279/', 'name': 'Miracle',
             'color': ['сиреневый', 'белый', 'многоцветный'], 'coutry': 'Россия',
             'size': ['5x44', '44x40', '44x20', '42x42'], 'price': '860'},
            {'link': 'https://www.rusplitka.ru/products/cersanit/sunrise-7349/', 'name': 'Sunrise',
             'color': ['бежевый', 'персиковый', 'розовый'], 'coutry': 'Россия',
             'size': ['88x40', '44x4', '44x20', '42x42'], 'price': '860'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/shebbi-shik-10478/', 'name': 'Шебби Шик',
             'color': ['белый', 'яркий', 'розовый'], 'coutry': 'Россия',
             'size': ['7x60', '60x60', '60x40', '60x20', '60.3x19.9'], 'price': '969'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/milaneze-dizayn-10974/', 'name': 'Миланезе Дизайн',
             'color': ['золотой', 'белый', 'кремовый', 'коричневый', 'чёрный', 'бежевый'], 'coutry': 'Россия',
             'size': ['6x60', '45x45', '30x30', '3.6x60', '20x60'], 'price': '441'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/vestanvind-10973/', 'name': 'Вестанвинд',
             'color': ['бежевый', 'серо-бежевый', 'белый', 'голубой'], 'coutry': 'Россия',
             'size': ['5x60', '3x60', '20x60'], 'price': '1009'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/fiori-grigio-11312/', 'name': 'Fiori Grigio',
             'color': ['серо-бежевый', 'бежевый', 'темно-серый', 'коричневый', 'серый', 'светло-серый'],
             'coutry': 'Россия', 'size': ['9x60', '60x80', '6.5x60', '45x45', '30x30'], 'price': '911'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/nordanvind-10975/', 'name': 'Норданвинд',
             'color': ['серо-бежевый', 'белый'], 'coutry': 'Россия', 'size': ['6.3x60', '20x60'], 'price': '1009'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/astrid-10786/', 'name': 'Астрид',
             'color': ['бежевый', 'коричневый', 'белый', 'черно-белый', 'кремовый', 'серый'], 'coutry': 'Россия',
             'size': ['6.3x40', '5.8x5.8', '30x30', '20x40'], 'price': '699'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/yaschiki-13180/', 'name': 'Ящики',
             'color': ['синий', 'бежевый', 'белый', 'песочный', 'серый'], 'coutry': 'Россия',
             'size': ['60x6.5', '60x20', '45x45'], 'price': '959'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/parizhanka-13301/', 'name': 'Парижанка',
             'color': ['многоцветный', 'синий', 'белый', 'бирюзовый', 'голубой', 'бежевый', 'серый'],
             'coutry': 'Россия', 'size': ['7x60', '7.5x60', '6x60', '20x60'], 'price': '1009'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/moreska-16746/', 'name': 'Мореска',
             'color': ['бежевый', 'многоцветный', 'белый', 'яркий', 'морская волна', 'синий'], 'coutry': 'Россия',
             'size': ['45x45', '40x4.9', '40x4.7', '20x40'], 'price': '791'},
            {'link': 'https://www.rusplitka.ru/products/lb-ceramics/loft-stayl-9892/', 'name': 'Лофт стайл',
             'color': ['серый', 'светло-серый', 'темно-серый'], 'coutry': 'Россия',
             'size': ['4x45', '45x45', '45x4', '45x25', '45x100'], 'price': '736'},
            {'link': 'https://www.rusplitka.ru/products/laparet/petra-15684/', 'name': 'Петра',
             'color': ['бежевый', 'серый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x5', '60x20', '60x2.9', '60x1.6', '5x60'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/aspen-15660/', 'name': 'Aspen',
             'color': ['бежевый', 'коричневый', 'белый', 'серый', 'песочный', 'золотой'], 'coutry': 'Россия',
             'size': ['60x20', '60x2.9', '60x1.6', '5x60', '40.2x40.2'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/kiparis-15669/', 'name': 'Kiparis',
             'color': ['бежевый', 'серый', 'белый', 'коричневый', 'песочный', 'золотой'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '40.2x40.2', '4.7x60', '38.5x38.5'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/platan-15647/', 'name': 'Platan',
             'color': ['бежевый', 'серый', 'белый', 'песочный'], 'coutry': 'Россия',
             'size': ['40.2x40.2', '4.7x40', '38.5x38.5', '20x40', '2.9x40'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/serenity-15654/', 'name': 'Serenity',
             'color': ['коричневый', 'бежевый', 'серый', 'кремовый'], 'coutry': 'Россия',
             'size': ['6x40', '40x40', '20x40', '2.9x40', '1.6x40'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/amber-14398/', 'name': 'Amber',
             'color': ['бежевый', 'серый', 'кремовый', 'песочный'], 'coutry': 'Россия',
             'size': ['6x60', '60x2.9', '60x1.6', '50x2.9', '50x1.6'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/atria-14399/', 'name': 'Atria',
             'color': ['бежевый', 'кремовый', 'серый'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '50x2.9', '50x1.6', '40.2x40.2'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/elektra-14400/', 'name': 'Elektra',
             'color': ['бежевый', 'серый'], 'coutry': 'Россия',
             'size': ['6x60', '60x2.9', '60x1.6', '50x2.9', '50x1.6'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/agat-14395/', 'name': 'Agat',
             'color': ['серый', 'кофейный', 'белый'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '50x2.9', '50x1.6', '40.2x40.2'], 'price': '1290'},
            {'link': 'https://www.rusplitka.ru/products/laparet/allure-14397/', 'name': 'Allure',
             'color': ['серый', 'серо-бежевый', 'светло-серый'], 'coutry': 'Россия',
             'size': ['6x60', '60x2.9', '60x1.6', '50x2.9', '50x1.6'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/fort-14401/', 'name': 'Fort', 'color': ['серый'],
             'coutry': 'Россия', 'size': ['60x2.9', '60x1.6', '50x2.9', '50x1.6', '40.2x40.2'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/havana-14402/', 'name': 'Havana',
             'color': ['серый', 'белый', 'бежевый', 'голубой', 'коричневый', 'многоцветный'], 'coutry': 'Россия',
             'size': ['60x2.9', '60x1.6', '50x2.9', '50x1.6', '40.2x40.2'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/zen-14405/', 'name': 'Zen',
             'color': ['белый', 'серый', 'бежевый', 'чёрный', 'коричневый', 'синий'], 'coutry': 'Россия',
             'size': ['6x60', '60x2.9', '60x1.6', '50x2.9', '50x1.6'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/prime-15100/', 'name': 'Prime',
             'color': ['серый', 'бежевый', 'чёрный', 'коричневый', 'оранжевый', 'белый'], 'coutry': 'Россия',
             'size': ['50x6', '50x25', '50x2.9', '50x1.6', '40.2x40.2'], 'price': '390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/spring-15101/', 'name': 'Spring',
             'color': ['голубой', 'розовый', 'золотой', 'белый', 'серый', 'многоцветный'], 'coutry': 'Россия',
             'size': ['50x25', '50x2.9', '50x1.6', '40.2x40.2', '25x25'], 'price': '1290'},
            {'link': 'https://www.rusplitka.ru/products/laparet/village-15102/', 'name': 'Village',
             'color': ['серый', 'бежевый', 'коричневый', 'белый', 'песочный', 'слоновая кость'], 'coutry': 'Россия',
             'size': ['50x6', '50x25', '50x2.9', '50x1.6', '40.2x40.2'], 'price': '578'},
            {'link': 'https://www.rusplitka.ru/products/laparet/olimpus-15099/', 'name': 'Olimpus',
             'color': ['чёрный', 'белый', 'серый'], 'coutry': 'Россия',
             'size': ['50x25', '50x2.9', '50x1.6', '40.2x40.2', '25x25'], 'price': '1290'},
            {'link': 'https://www.rusplitka.ru/products/laparet/eco-16860/', 'name': 'Eco',
             'color': ['серый', 'белый', 'золотой', 'коричневый'], 'coutry': 'Россия',
             'size': ['75x3', '75x25', '75x2.9', '75x1.6', '75x1.5'], 'price': '461'},
            {'link': 'https://www.rusplitka.ru/products/laparet/lilit-16862/', 'name': 'Lilit',
             'color': ['серый', 'белый', 'золотой', 'голубой', 'коричневый'], 'coutry': 'Россия',
             'size': ['75x3', '75x25', '75x2.9', '75x1.6', '75x1.5'], 'price': '413'},
            {'link': 'https://www.rusplitka.ru/products/laparet/escada-18102/', 'name': 'Escada',
             'color': ['серый', 'белый'], 'coutry': 'Россия',
             'size': ['60x20', '60x2.9', '60x1.6', '40.2x40.2', '2.9x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/happy-18103/', 'name': 'Happy',
             'color': ['бежевый', 'золотой'], 'coutry': 'Россия', 'size': ['60x3', '60x20', '60x1.5', '40.2x40.2'],
             'price': '1390'}, {'link': 'https://www.rusplitka.ru/products/laparet/lord-18104/', 'name': 'Lord',
                                'color': ['белый', 'серый'], 'coutry': 'Россия',
                                'size': ['60x20', '60x2.9', '60x1.6', '40.2x40.2', '20x60'], 'price': '1290'},
            {'link': 'https://www.rusplitka.ru/products/laparet/select-18107/', 'name': 'Select', 'color': ['серый'],
             'coutry': 'Россия', 'size': ['60x20', '60x2.9', '60x1.6', '40.2x40.2'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/betonhome-17567/', 'name': 'Betonhome',
             'color': ['серый', 'коричневый', 'белый', 'светло-серый', 'бежевый', 'золотой'], 'coutry': 'Россия',
             'size': ['60x60', '59.7x14.8', '50x20', '50x2.9', '50x1.6'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/elegance-19090/', 'name': 'Elegance',
             'color': ['серый', 'белый', 'серо-бежевый'], 'coutry': 'Россия',
             'size': ['60x60', '59.7x14.8', '50x20', '50x2.9', '50x1.6'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/venus-18138/', 'name': 'Venus',
             'color': ['серый', 'золотой', 'белый', 'бежевый', 'коричневый'], 'coutry': 'Россия',
             'size': ['40x3', '40x20', '40x1.5', '40x1.2', '40.2x40.2'], 'price': '990'},
            {'link': 'https://www.rusplitka.ru/products/laparet/eden-18292/', 'name': 'Eden',
             'color': ['голубой', 'золотой'], 'coutry': 'Россия', 'size': ['60x3', '60x20', '60x1.5', '40.2x40.2'],
             'price': '590'}, {'link': 'https://www.rusplitka.ru/products/laparet/aragon-18290/', 'name': 'Aragon',
                               'color': ['белый', 'золотой', 'бежевый'], 'coutry': 'Россия',
                               'size': ['60x60', '60x3', '60x20', '60x1.5'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/monti-18295/', 'name': 'Monti',
             'color': ['чёрный', 'серый', 'белый'], 'coutry': 'Россия',
             'size': ['60x20', '60x2.9', '60x1.6', '40.2x40.2'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/viva-18297/', 'name': 'Viva',
             'color': ['белый', 'серый'], 'coutry': 'Россия',
             'size': ['60x20', '60x2.9', '60x1.6', '40.2x40.2', '20x60'], 'price': '1390'},
            {'link': 'https://www.rusplitka.ru/products/laparet/fronda-19093/', 'name': 'Fronda',
             'color': ['бежевый', 'серый', 'золотой', 'белый', 'слоновая кость'], 'coutry': 'Россия',
             'size': ['50x3', '50x20', '50x2.9', '50x1.6', '40.2x40.2'], 'price': '590'},
            {'link': 'https://www.rusplitka.ru/products/laparet/fumo-19088/', 'name': 'Fumo',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'size': ['50x20', '50x2.9', '50x1.6', '40.2x40.2'],
             'price': '1090'}, {'link': 'https://www.rusplitka.ru/products/laparet/soul-19086/', 'name': 'Soul',
                                'color': ['бежевый', 'серый', 'коричневый', 'кремовый'], 'coutry': 'Россия',
                                'size': ['60x15', '50x20', '50x2.9', '50x1.6'], 'price': '690'},
            {'link': 'https://www.rusplitka.ru/products/laparet/next-18502/', 'name': 'Next',
             'color': ['серый', 'белый'], 'coutry': 'Россия', 'size': ['60x15', '50x25', '50x2.9', '50x1.6'],
             'price': '1190'}, {'link': 'https://www.rusplitka.ru/products/laparet/laurel-18654/', 'name': 'Laurel',
                                'color': ['белый', 'серый', 'синий', 'золотой', 'коричневый'], 'coutry': 'Россия',
                                'size': ['60x60', '60x30', '60x3', '60x15', '60x1.5'], 'price': '1190'}]
